version: '3.8'

services:
  # -----------------------------
  # 1. Banco de Dados (PostgreSQL)
  # -----------------------------
  db:
    image: postgres:15-alpine
    container_name: seucantinho-db
    restart: always
    environment:
      POSTGRES_DB: seucantinho
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cantinho-net

  # -----------------------------
  # 2. Backend (Spring Boot)
  # -----------------------------
  api:
    build: ./backend
    container_name: seucantinho-api
    restart: on-failure
    depends_on:
      - db
    environment:
      # Note que usamos o nome do servi√ßo 'db' como host
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/seucantinho
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - cantinho-net

  # -----------------------------
  # 3. Frontend (Angular)
  # -----------------------------
  web:
    build: ./frontend
    container_name: seucantinho-web
    restart: on-failure
    ports:
      - "8081:80"
    depends_on:
      - api
    networks:
      - cantinho-net

networks:
  cantinho-net:
    driver: bridge

volumes:
  postgres_data: